install:
  - choco install jq
  - choco install rsync
  - node --version
  - npm --version
  - npm install
  - pip upgrade pip
  - pip install pipenv
  - pipenv install cram
  - bash ./tests/pre-download-elm-packages.sh

build: off

test_script:
  - bash ./tests/make_links.sh
  - pipenv run cram -v ./tests
